// TODO Need to confirm this is all accurate
var CoasterStyles = {
	"unknown": { hasGates: true, hasHarness: false, hasMovableFloor: false, hasFlyingCar: false, name: "Unknown" },
	0: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Classic Looping" },
	1: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Arrow Corkscrew" },
	2: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Arrow Inverted" },
	3: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "B&M - Sitdown" },
	4: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "B&M - Inverted" },
	5: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Intamin Hyper" },
	6: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "B&M - Floorless" },
	7: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "B&M - Standup" },
	8: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "B&M - Hyper" },
	9: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Wooden - Trailered" },
	10: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Wooden - Classic 4 Seat" },
	11: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Wooden - Classic 6 Seat" },
	12: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Wooden - Trailered 4 Seat" },
	13: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "LIM Launched" },
	14: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Inverted Face to Face" },
	15: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Inverted Impulse" },
	16: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Suspended" },
	18: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: true, name: "Flying Dutchman" },
	20: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Maurer Spinning" },
	21: { hasGates: true, hasHarness: true, hasMovableFloor: true, hasFlyingCar: false, name: "Dive Coaster" },
	22: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "4D" },
	23: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: true, name: "B&M - Flying" },
	33: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Rocket Coaster" },
	34: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Mine Train - Without Locomotive" },
	35: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Mine Train - With Locomotive" },
	36: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Gerstlauer Eurofighter" },
	38: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Vekoma Motorbike" },
	39: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Gerstlauer Bobsled" },
	41: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Gerstlauer Spinning" },
	47: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Gerstlauer Eurofighter 2" },
	49: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Classic Looping - Modern" },
	50: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Maurer X-Car" },
	55: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Zamperla Spinning" },
	62: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Mack Launch" },
	63: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Hyper - 4 Seat Staggered" },
	64: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Hyper - 4 Seat Staggered with water scoops" },
	71: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Timberliners" },
	73: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Gerstlauer Infinity" },
	74: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "Gerstlauer Infinity 2" },
	76: { hasGates: true, hasHarness: true, hasMovableFloor: false, hasFlyingCar: false, name: "B&M - Wing" },
};

var StationState = {
	"None": 0,
	"EmergencyStop": 1,
	"ManualDispatch": 2,
	"CanDispatch": 4,
	"CanCloseGates": 8,
	"CanOpenGates": 16,
	"CanCloseHarness": 32,
	"CanOpenHarness": 64,
	"CanRaisePlatform": 128,
	"CanLowerPlatform": 256,
	"CanLockFlyerCar": 512,
	"CanUnlockFlyerCar": 1024,
};
